import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import { getServerSession } from "next-auth";
import AuthProvider from "@/config/AuthProvider";
import { CartProvider } from "@/config/CartProvider";
import { Toaster } from "sonner";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getServerSession();
  return (
    <html lang="en" className="bg-orange-100">
      <body className={`mx-auto max-w-screen-xl antialiased`}>
        <AuthProvider session={session}>
          <CartProvider>
            <Toaster richColors position="bottom-center" />
            <Header />
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
