import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import { getServerSession } from "next-auth";
import AuthProvider from "@/config/AuthProvider";
import { Toaster } from "sonner";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getServerSession();
  return (
    <html lang="en">
      <body className={`antialiased max-w-screen-xl mx-auto`}>
        <AuthProvider session={session}>
          <Toaster richColors position="bottom-center" />
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
